### ISSUE TITLE
C++14 compliance issue in Ppu::RenderTilemapMode7

### ISSUE THREAD

**Issue by Myriachan** [SourMesen/Mesen-S#11]
```C:\Projects\Mesen-S\Core\Ppu.cpp(850): error C2127: 'clip': illegal initialization of 'constexpr' entity with a non-constant expression```

Lambdas cannot be `constexpr` until C++17:

```constexpr auto clip = [](int32_t val) { return (val & 0x2000) ? (val | ~0x3ff) : (val & 0x3ff); };```

To fix this, change Core's project settings to say C++17 in Properties / C/C++ / Language / C++ Language Standard.  Or remove `constexpr`.

This breaks compilation on MSVC 2019.

**Comment by SourMesen** [comment]
Thanks, this is pretty much the same as #8 but for VS2019.  Hadn't noticed that the error was actually a single line, so that was an easy fix!

I removed constexpr (b1a50434c97c574004af0e976ecb3533c6dc60a3), it had no real impact either way, and I'd rather not require C++17 for compilation just yet.
