### ISSUE TITLE
Tales of Phantasia

### ISSUE THREAD

**Issue by NiBBa256** [SourMesen/Mesen-S#125]
![Tales of Phantasia  T+Eng1 2 _000](https://user-images.githubusercontent.com/47758660/82728782-e10d8600-9cf2-11ea-8f31-5a51fd2c0ff6.png)
Tales of Phantasia just gives this garbage.

**Comment by SourMesen** [comment]
Based on the name of the image you posted (Tales of Phantasia  T+Eng1 2 _000), you are probably using the super old Dejap translation patch, rather than just the original game?  This apparently needs to be applied to very specific older roms that aren't really available anymore - odds are you are applying the patch to the wrong rom file. 

I found another more up-to-date patch here: https://www.romhacking.net/translations/2335/
This one seems to run just fine.

**Comment by NiBBa256** [comment]
I dunno, it runs just fine in the latest SNES 9X version.
The patch you provided is a no go, as it doesn't contain the original voice clips, but it was dubbed. Are there patches with the audio dialog intact?

**Comment by SourMesen** [comment]
It's a bit hard to help without knowing what patch you are using, or what rom you are using. I grabbed the original dejap patch from here: http://www.romhacking.net/translations/474/
And used the TOP_DX2L.IPS file to patch a headered rom following the instructions in the readme that comes with the patch: `The patch requires an original Japanese rom with a 512 byte header, making it 6,291,968 bytes in size. If the rom is only 6,291,456 bytes, it does not have a header`

Headered roms are fairly uncommon today, but that is what the patch is meant to be used against. I took the unheadered game and added 512 bytes at the start of it to turn into in a headered rom, which allowed the patch to load up properly. My best guess is that snes9x internally tries to add a header if it somehow detects that the patch appears to have resulted in a bad rom? Hard to say.

Hope that helps,
