### ISSUE TITLE
running GB Compatible Game Boy Color games

### ISSUE THREAD

**Issue by bETAmEN** [SourMesen/Mesen-S#140]
SGB Enhanced / GB Compatible Game Boy Color games always run in GBC mode. Is there any way to force games to start in GB mode?

**Comment by SourMesen** [comment]
There is a dropdown in Options -> Emulation -> Game Boy that will allow you to select a specific GB model, instead of picking the (subjective) "best" based on what the game is.

Also, just as a heads up, the whole GB/GBC/SGB emulation part of things is very new, and still being worked on, so expect save states, etc. to break from one build to another.

Edit: The model option was moved to Options -> Game Boy -> General

**Comment by ghost** [comment]
Sorry to pop into a closed issue...but I can't get any Game Boy Color games to load at all. Just a black screen forever. I don't have a `Game Boy` option in my dropdown. Not in Emulation either. Running 0.4.0.

Perhaps logs like this are useful?

```
-----------------------------
File: Pokemon - Crystal Version (USA, Europe).zip
Game: ��0��n7���W6�	+�B�
Game code: Z}-�
Type: LoROM
FastROM
Copier header found.
Map Mode: $B9
Rom Type: $01
File size: 1005 KB
ROM size: 1 KB
SRAM size: 256 KB
-----------------------------
-----------------------------
File: Pokemon Pinball (USA, Australia) (Rumble Version) (SGB Enhanced) (GB Compatible).zip
Game: ��<ez�ާ^|*�i���>���9
Game code: ����
Type: HiROM
FastROM
Copier header found.
Map Mode: $9F
Rom Type: $32
File size: 307 KB
ROM size: 0 KB
SRAM size: 256 KB (with battery)
-----------------------------
```
