### ISSUE TITLE
Naming of GB/GBC and SGB bios files

### ISSUE THREAD

**Issue by paradadf** [SourMesen/Mesen-S#141]
Hi and thanks for the emulator!
I'd like to suggest you to use the naming convention used by mgba (and others) for the respective bios, as can be seen here:

https://docs.libretro.com/library/mgba/#bios

BR

**Comment by SourMesen** [comment]
Unfortunately, not all the existing GB cores use the same filenames for these. 

I just added the mGBA naming convention as a set of alternative names that can be used (73afbc362314a2b7bcdaf166474b70c0f5b4e0a6), so that people that have those files already don't need to rename or copy them (but the core info will still only list the current SameBoy naming convention, to avoid confusion)

**Comment by paradadf** [comment]
That's more than good enough! Thanks!
