### ISSUE TITLE
HDMA test & spc_dsp6

### ISSUE THREAD

**Issue by Max833** [SourMesen/Mesen-S#142]
There seems to be something wrong on the right-hand side.

Test rom: https://github.com/PeterLemon/SNES/tree/master/PPU/HDMA/HiColor64PerTileRowPseudoHiRes 

![image](https://user-images.githubusercontent.com/53529402/86340961-f1037880-bc55-11ea-9523-58e9063b4552.png)

![image](https://user-images.githubusercontent.com/53529402/86340969-f3fe6900-bc55-11ea-8fef-63d21223c86b.png)

**Comment by Max833** [comment]
spc_dsp6 test (https://gitlab.com/higan/snes-test-roms/-/tree/master/blargg-spc-6):

![image](https://user-images.githubusercontent.com/53529402/86369499-d2fe3e00-bc7e-11ea-9b94-ff653203a72d.png)

![image](https://user-images.githubusercontent.com/53529402/86369509-d5f92e80-bc7e-11ea-940e-101a90de9ca7.png)

**Comment by SourMesen** [comment]
Thanks for the reports!

The SPC test rom fails because cubic interpolation is turned on (I accidentally made the option default to being enabled when I added it - it defaults to disabled now) - you can disable it in Audio->Advanced and it should fix the test.

The HDMA test was a small bug with color math when using high res mode and also reading/writing PPU registers in the middle of the scanline (unsure if any commercial game actually does this specific combination anywhere) - should be fixed now, too.

**Comment by Max833** [comment]
Wow, that happened quickly. You're welcome! :)
