### ISSUE TITLE
SNES Mosaic effect 

### ISSUE THREAD

**Issue by Max833** [SourMesen/Mesen-S#145]
I hope it is okay to post some things I've noticed...

Game: Energy Breaker (Japan)
Issue: Push the start button in the menu. The last mosaic line seems to be a little bit off.

![image](https://user-images.githubusercontent.com/53529402/86530122-6c636500-beb6-11ea-901e-2d9f6ad90c6c.png)

![image](https://user-images.githubusercontent.com/53529402/86530123-6ff6ec00-beb6-11ea-91dd-fdf142eb24d3.png)

**Comment by SourMesen** [comment]
> I hope it is okay to post some things I've noticed...

Absolutely - please report anything you happen to notice, these kinds of reports are very helpful.

This one was another issue similar to the one you reported for the hdma test rom earlier - reads/writes to the PPU in the middle of a scanline was triggering a bug in the mosaic calculation which caused it to display incorrectly.  This is fixed with 98fe9a85d658dbb3d9dd1aa43b3639cf7efc4713
