### ISSUE TITLE
Blargg Controller Strobe Behavior Test - Fails

### ISSUE THREAD

**Issue by Zenjir0** [SourMesen/Mesen-S#21]
Just wanted to inform that when performing one of Blargg's SNES Hardware Test ROMs, the Mesen-S emulator does not seem to report the correct Controller Strobe Behavior, and fails the test.

Both Bsnes/Higan, and Snes9x pass the test.

Test ROMs can be found here if needed:
https://snescentral.com/homebrew.php

I know you have a webpage for your NES Accuracy: https://mesen.ca/#Accuracy
Didn't know if there will be one for SNES.

**Comment by SourMesen** [comment]
Thanks - I think I've run that test rom at one point never got around to figuring out why it failed. I'll try to take a look soon, doesn't sound like something that would be hard to fix.

**Comment by SourMesen** [comment]
Thanks for the report - this should be fixed by a76f76580390ab8fa975bd1f17d2fd55d7ddda57.

I probably won't make a test rom chart for the SNES - there are (currently) too few in-depth test roms for them to really be meaningful, and the one I made for Mesen was originally just my way of making people aware that the NES test roms charts on tasvideos.org were somewhat outdated (esp. since I had no way to add Mesen's result on that page).  Plus, I really don't want to start a "who can pass the most test roms" war with other snes emulators, either!
