### ISSUE TITLE
Caravan Shooting Collection (Japan) (En)

### ISSUE THREAD

**Issue by Max833** [SourMesen/Mesen-S#32]
Start the third game and look at the top. Some flickering is going on there. ^^;

bsnes: https://streamable.com/2rdju

Mesen-S: https://streamable.com/v7qhf

**Edit:** Sound seems to be a little bit off as well.

**Comment by SourMesen** [comment]
(Sorry for the delay in getting back to you about all these things, btw.)

It looks like the bsnes video is at 224px whereas Mesen-S is at 239px, which could certainly explain the bugged row at the top.  I'll have to check if it's just a matter of bsnes defaulting to cutting off the top/bottom part of the screen in this scenario (Mesen-S displays 239px at all times, unless you manually cut it off using the overscan settings.)

Also, for a second I thought I was looking at a bug report for Mesen because of the game :p

**Comment by SourMesen** [comment]
Finally took a look at this, and it looks like this is normal.
The top 7-8 pixels are actually bugged in bsnes-plus/snes9x, too, if you make them show the whole 239px picture (not sure how to do this in regular bsnes, if it's possible at all.)

Given that this looks like a NES/Famicom port, it's not too surprising that it does this, either.
