### ISSUE TITLE
Chester Cheetah - Too Cool to Fool (USA) - sound issue

### ISSUE THREAD

**Issue by Max833** [SourMesen/Mesen-S#33]
- screenshot 1: when you want to go to "option" and press select, you can't hear sound
- screenshot 2: when you want to collect those coins(?), you can't hear anything either

 There are no problems with bsnes or snes9x Edit: and hardware.

![aaa](https://user-images.githubusercontent.com/53529402/63860486-833d4f00-c9a9-11e9-82aa-2184f679d47d.jpg)

**Comment by ghost** [comment]
years ago this had audio trouble in snes9x and got fixed. I remember. Probably same issue as it had.

**Comment by SourMesen** [comment]
It's likely to be some sort of timing issue then - if the game expects very specific SPC/CPU timings, it might be breaking due to them being ever so slightly off in some scenarios still (compared to higan).  It might work on snes9x because the timings are off enough that the game starts working again.  AFAIK, Kishin Douji Zenki - Tenchi Meidou is another game that currently freezes on boot because of the SPC<->CPU timings.

**Comment by SourMesen** [comment]
After looking at this for what feels like the 5th time and digging a bit more, I finally found the cause!

blargg's DSP core initializes the KOF register ($5C) with the value $9C.  This game never seems to write to $5C, so this causes some of the sound channels to be permanently muted.  Initializing KOF to 0 instead fixes the issue (d5c4204bb31c75093554349833bcb5b8178d9610).  This also fixes another game (King of Dragons) which had missing sound effects like this game.
