### ISSUE TITLE
Crayon Shin-chan - Arashi o Yobu Enji (Japan) - weird fog effect

### ISSUE THREAD

**Issue by Max833** [SourMesen/Mesen-S#34]
https://github.com/byuu/bsnes/issues/73

**Comment by SourMesen** [comment]
Thanks for the report!

This is basically just caused by a lack of blending in high resolution modes.  Turning on the NTSC filter fixes this, but since this was also something that was requested before, I've added a "blend high resolution modes" option (similar to an option in snes9x) to allow these kinds of effects to show up properly without requiring the NTSC filter (5fc711881176cc515cd130295c108393f17376cf)
