### ISSUE TITLE
Keep rewind data for the last 30 minutes cannot be changed

### ISSUE THREAD

**Issue by ghost** [SourMesen/Mesen-S#37]
Whenever you set the Keep Rewind Data option to something other than 30 minutes, it doesn't stick.  Pressing OK and then coming back to the option it is always stuck at 30.  Exiting and reopening the emu doesn't make the setting change either.

As an aside, why doesn't this have a "Disable Game Selection Screen" option in Preferences/Advanced like Mesen does?  I like that option and honestly wished it was turned on by default.  And why no Turbo button option either?

Another thing I'd like to add is how good this emulator is.  I've been playing Wild Guns and it plays much better than Snes9x.  The controls are much tighter and the collision detection is on point (Snes9x hiccups a lot with this game).  And everything just looks smoother, even Blargg's filter has the slight jitter like a real television of the time if you look closely enough.

**Comment by SourMesen** [comment]
Thanks for the report - the rewind duration bug was fixed a while ago, the latest dev builds should already have the fix in them.

RE: Disable game selection screen & turbo, they're not in simply because I haven't had the chance to add them mostly - can't do everything at once!  I'll keep this opened until I get around to adding those options.

Happy to hear you're enjoying it!  Let me know if you find anything else.

**Comment by SourMesen** [comment]
The option to disable the game selection screen and turbo button bindings have been added, so everything mentioned in this issue should be fixed now.
