### ISSUE TITLE
Cheats

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen-S#48]
Will we see a Cheat finder like Mesen has? Will Mesen-S be able to use Snes9s 1.60 Cheat codes someday? Also Snes9x 1.60 had a search database here is the search database file.

[cheats.zip](https://github.com/SourMesen/Mesen-S/files/3726722/cheats.zip)

**Comment by SourMesen** [comment]
There is a cheat database in Mesen-S already, it should essentially be the same as the one in bsnes (since bsnes uses Mighty Mo's DB, afaik). I'm unsure if snes9x's cheat DB is the same, but snes9x's license is not GPL-compatible so it can't be included.

There will probably be a cheat finder eventually, but I'm not a big fan of the cheat finder's UI in Mesen and would rather try to come up with something better rather than reuse the same code, so it will probably be a while until I get around to it (there are a lot more things I would rather focus on right now)

**Comment by Cibomatto2002** [comment]
Sorry but I don't see the cheat database. this is all I see. I really like  the cheat finder in Meson it's easy to use. 
![Capture2-26-2019-1 00 36 AM4-13-2019-1 36 54 PM10-14-2019-7 03 07 PM](https://user-images.githubusercontent.com/21169038/66790487-81760f00-eeb5-11e9-9c2d-2fc53a44493e.jpg)

**Comment by SourMesen** [comment]
You must not be using the latest build then - the cheat DB was added last night and should be in 0.2.0.38 and up.

**Comment by Cibomatto2002** [comment]
I had 0.2.37 sorry.
