### ISSUE TITLE
feature request (resolution)

### ISSUE THREAD

**Issue by ghost** [SourMesen/Mesen-S#49]
Both Mesen and Mesen-S have become an emulator I use daily. both lack one feature I find very important.

The ability to select screen resolution.

Those of us using giant screens on media centers or those of us using a weaker machine can benefit greatly if we have the option to set different exclusive full screen resolution rather than desktop resolution.

most stand alone emulators till recent did this.

Examples can be seen in Mednafen, snes9x, nestopia ue, kega fusion etc.

Please consider adding this ability one day.

Thank you.

**Comment by obunden** [comment]
I'm no expert and I don't have any older hardware to test on, but to me it feels like the resolution isn't a big deal if you have performance issues. If you can't get full fps in your native screen resolution it's probably because of the hardware can't emulate quick enough and not the actual image rendering. 

I assume that the emulator just upscales to the resolution on the device where it is displayed? And if you have a high resolution monitor you probably aldready have it configured correctly and you wouldn't care about the possible performance gains of lower resolutions. I know that if you make certain applications fullscreen in windows they will always be displayed on the primary screen. If this is the case with mesen you could try retroarch that lets you define which screen you want to use and if you want to use windowed fullscreen or not.

One real benefit of the resolution switcher would be if you are using a CRT monitor/TV. But frankly that is better left to projects like retroarch that can change resolutions on the fly depending on the core/game imo.

**Comment by ghost** [comment]
in my case I'm using a 65 inch 4k tv on a media center at a distance and use a different res for my desktop at a distance than native on modern hardware and would like the ability to change res for gaming.

**Comment by ghost** [comment]
not for performance as assumed.

**Comment by ghost** [comment]
I love how people assume always these days that wanting a different resolution means your computer is slow. they don't seem to grasp we live in a world where differnt people have different configurations. lucky OS developers and AAA game developers aren't that closed minded.

**Comment by obunden** [comment]
I don't assume anything, I just brought up the different use cases that I could think of and you did mention that it would be good for people that had weaker machines. Since you had a big screen I figured performance wasn't the problem in your case.

With that said changing the native screen resolution isn't something that I would encourage in any setup, regardless of screen size or computer specs (except for CRTs), but I suppose it might be useful if you are using a OS or application that doesn't handle custom DPI scaling. If you still want to go this route you will lower your image quality, introduce risks for tearing and input lag. if the reason for this is visibility then that should be handled by the OS/proper coded applications. not by changing resolutions.

This is just my take on things and my personal opinions, in the end it's up to the dev what is the right thing for this project or if anyone wants to help out and get it rolling and implement it.

**Comment by SourMesen** [comment]
This is available as of 5e900992d09825f60acb7a3e2369fe4460cb3848.
Let me know if you have issues with it.
