### ISSUE TITLE
Color Question

### ISSUE THREAD

**Issue by Awakened0** [SourMesen/Mesen-S#56]
I'm kind of curious about the difference in colors between bsnes and Mesen-S: http://www.framecompare.com/image-compare/screenshotcomparison/DW66GNNX

It's subtle, but if you look at the grey background, you can see bsnes is a little more reddish, while Mesen-S is more green. Personally I find bsnes' color output a little more pleasing, but I don't know which is more accurate or the reason for the difference.

**Comment by SourMesen** [comment]
Your screenshot uses color `rgb(107,104,107)` for the gray background in bsnes, but my copies of bsnes 107 (not libretro) and bsnes-plus have that gray set to `rgb(107,107,107)` (which makes more sense)

Mesen-S used `rgb(106, 107, 106)` because of rounding errors for some of the hue/contrast calculations, but I just fixed it (026be87dfbaf66dd31af8eedf3f9cd04a0703f38) to skip those calculations when all the parameters are set to their default values, so now it correctly outputs `rgb(107,107,107)`

As far as I can tell, `rgb(107,107,107)` is correct - the original 5-bit color used is 13,13,13, which turns into 107 when converted to 8-bit.

So I'm not sure why bsnes is using 104 for the green channel in your screenshot.  Either a Retroarch setting/filter or an issue in bsnes' libretro core?

**Comment by Awakened0** [comment]
Both screenshots are from the latest builds of their libretro cores. I'm using the same settings for both; no color correction, just an interpolation shader (bandlimit-pixel). Maybe it's something with how RetroArch handles RGB1555, which bsnes uses. I guess RetroArch converts it to 565, [from what this comment says](https://www.reddit.com/r/emulation/comments/d6tel1/bsnes_v110_released_byuu/f0wed6v/?utm_source=share&utm_medium=web2x). That flickering bug was fixed, but I think the conversion still happens.

**Comment by SourMesen** [comment]
Assuming RetroArch uses 565, my best guess would be that the extra conversion (5-bit -> 6-bit -> 8-bit) might be causing the final 8-bit value to be slightly different?

The Mesen-S core always outputs in 32-bit ARGB8888, so RetroArch is most likely just using that as-is rather than converting to another format.

**Comment by Awakened0** [comment]
Well, sounds like it's correct then. Thanks for the info!
