### ISSUE TITLE
Total Football (Europe) - glitchy menu and game doesn't start

### ISSUE THREAD

**Issue by Max833** [SourMesen/Mesen-S#57]
Edit: It's a prototype. Closed.

Mesen-S:
![image](https://user-images.githubusercontent.com/53529402/68078043-273ede80-fdcf-11e9-8309-e7374845cbef.png)

bsnes:
![image](https://user-images.githubusercontent.com/53529402/68078053-56555000-fdcf-11e9-845b-3a75213f18b4.png)
![image](https://user-images.githubusercontent.com/53529402/68078112-42f6b480-fdd0-11e9-8376-6d6a7d39915b.png)

**Comment by SourMesen** [comment]
Please do report broken prototypes, especially if they work in bsnes/higan.

@byuu
In this case it looks like the game has no valid header, ends up being treated as lorom (which is correct.)  The header by pure luck has 0xFD in the save ram size byte - this ends up giving it 256kb of sram in bsnes.  Until a recent change you did, bsnes gave it 32kb of sram instead.

I have no idea how much sram the prototype actually has, though, but it definitely requires some amount of sram to work properly.  Just figured I'd let you know since you might want to add an entry in your database for it? (esp. since it kinda works by sheer chance atm and the sram value assigned by bsnes might change again if you were to decide to allow bigger sram sizes for homebrew, etc.)  It *is* just a prototype though.

For now, I've fixed this by applying the same logic as bsnes (ANDing the value with 0x0F and using 8 as a maximum value)
