### ISSUE TITLE
Games drop fps when loaded multiple times

### ISSUE THREAD

**Issue by Deivmsr** [SourMesen/Mesen-S#64]
I have tried Mesen-S as libretro core on Android. The same problem occurs the same way on two smatphones. I was previously running a Galaxy Note 8, Exynos processor version, and now I'm running Galaxy Note 9, Snapdragon 845. After upgrading the libretro core and running a rom, the game runs at 60 fps, but when you close Retroarch, go back to the home screen, open Retroarch again, and load rom from the "recent games" menu or going to the directory the file is in: the game runs between 49-51 fps and stuttering sound. There were two games tested: Aladdin and Mega Man X3. I used the Brazilian Portuguese to English translator and, if it is not clear what I wrote, please tell me that I will seek to improve the translation.

**Comment by SourMesen** [comment]
I saw you posting something similar on the RetroArch discord server, but you mentioned bsnes also had the same problem?  In that case, it's more likely to just be an issue with either RetroArch itself, or the hardware/OS running slightly faster/slower based on how the RAM is allocated, etc.

You mentioned that snes9x doesn't have this issue, but snes9x is also quite a bit faster, so even if it were slowed down in the same way, it would still run well above 60fps on your device.

**Comment by Deivmsr** [comment]
Yes, with bsnes this same problem happens. But if it's something from Retroarch, could something be done? Because I have tested both games several times today and it seems to have something to do when the device gets hot and, even a little hot, the Snes9x has no performance drop. But there was a version of Mesen-S where this problem did not occur, I think some committ of version 0.2.0. I think it was after CX4 chip support was introduced.

**Comment by obunden** [comment]
I've never tried retroarch on android so I can't really help with trying to replicate this. Since the issue seem to be casued by "restarting" retroarch it might be that it is still using resources in the background that doesn't get unallocated. Does this still happen if you do a "Forced Stop" on the app before reopening it? One guess would be that Mesen-S / Bsnes just uses more resources than snes9x and that is why you are not getting the same issue.

It's probably best to get in touch with the retroarch team and see if there are any known issues regarding this. Are you using retroarch 1.8.1 from google store?

**Comment by Deivmsr** [comment]
I tested Mesen-S forcing it out, but it didn't work out. Even so, the drop in fps continues. I tested both the nightly version and the Play Store version and the result is the same. But I found something I don't know if it can apply to Mesen-S. Bsnes also has this similar problem so when the game starts to run at 50 to 55 fps I hit the "recent apps" button and then I went back to Retroarch and played it back to 60 fps but that didn't had an effect on Mesen-S. I also tried to do a procedure that a guy from Retroarch gave me: while there is a drop in fps go to the video setup and hit "start" or the "space" key in "estimated screen framerate" to get back to 0. That made it Mega Man X3 and Aladdin runs again at 60 fps at bsnes core, but did not produce the same result at Mesen-S. But I don't know if anything was done to make Mesen-S maintain this "estimated screen framerate" to maintain performance. Did you understand all this?

**Comment by obunden** [comment]
I think I understood what you said. If force restarting the actual retroarch app doesn't fix it how do you get back to full fps in mesen-s? Do you need to restart the phone? I might be misunderstanding what you meant by "forcing out", but if the app is indeed completely shutdown that would logically reset everything. And if it really doesn't help I can't think of any issues that would be able to persist after that so I'm sadly out of ideas at that point.

Hopefully someone else can verify this issue that you are experiencing.

**Comment by Deivmsr** [comment]
This problem really happens when the phone gets hot. However, I want to point out that the core of Snes9x does not have this problem. But in Mesen-S, I noticed an improvement: the game starts to go wrong at 45-50 fps, but then the fps goes up to 60 during the game. If it was possible to keep a constant to avoid these drops, the emulator would be better to use. I raise this question because Mesen-s is a new project and I believe that on Android it has the potential to achieve stable performance. You who are most involved with this project could test this core on other platforms, not just the PC. Without disregarding those who prefer the PC, but only to make this cross-platform emulator just like others.

**Comment by SourMesen** [comment]
If it's because of the heat, then that's just the phone slowing down to avoid overheating, and by slowing down its making Mesen-S drop below 60 FPS in games. FPS can vary in a game from one scene to another, that's normal and mostly depends on what the game is doing.

Making Mesen-S run without slowdown on your phone is a matter of optimization - I can't really promise anything there.  I'm still in the middle of actually developing the emulation core, so trying to optimize it aggressively is something that is not an immediate priority.

**Comment by Deivmsr** [comment]
I really didn't know what stage Mesen-s was at. I am pleased with the answer and if you want to close this topic you can close.

**Comment by SourMesen** [comment]
Alright - closing this for now.  Thanks!
