### ISSUE TITLE
Feature Request: Per-game Graphical Settings

### ISSUE THREAD

**Issue by icup321** [SourMesen/Mesen-S#65]
Okay, I know this is something very big and complicated to request, but I think Mesen-S (and also probably Mesen) would greatly benefit from having an option to use per-game graphical settings. The main reason why I really want this is because SNES games were designed to be played in either 4:3 or 8:7 and since the SNES didn't really have a standard aspect ratio, so it was up to developers to choose which one they preferred. Naturally, this means that every time I want to play a game that was made for 4:3 or 8:7 aspect ratio I have to manually test and see which aspect ratio I should use every time so adding this would be useful. This could also be useful for creating a list of SNES games to see which ones they're meant to be played with.

Actually, another idea I thought about instead of adding per-game GFX settings would be to instead add an option to auto-detect which aspect ratio to use for the game currently loaded based on a database file, but that would require testing every single SNES game's aspect ratio and compiling them into a list.

**Comment by SourMesen** [comment]
I'm not sure I'm entirely understanding the issue here - is there a way for a game to switch between different aspect ratios?  Or do you just mean that some of them look better in 8:7 vs 4:3?
As far as I understand, all games shown on a CRT NTSC display back then should be using the 8:7 ratio?

**Comment by icup321** [comment]
What I mean is that some games look better in 4:3 rather than 8:7 and vice versa, since a lot of people used 4:3 TVs in the 90's, some developers (mostly third parties) programmed their games with 4:3 in mind rather than the original aspect ratio SNES was supposed to use (8:7), which first party developers like Nintendo and Rare stuck to. This video gives some examples of what I'm talking at around 3:30: [https://www.youtube.com/watch?v=ssluTgfkdlg](url)

**Comment by FitzRoyX** [comment]
>  which aspect ratio to use for the game currently loaded based on a database file,

Goodness, that would be a monumental task. Even if you completed that somehow, it disregards a major issue with aspect correction: "define your own pixel" displays are dead. It's a fixed grid of squares now, and that means line distortion if you attempt to simulate rectangles with them. Is it worth constantly distorting lines in order for 5 seconds of gameplay to show a proper large circle? That's clearly a poor tradeoff.

We're actually quite fortunate that the stretch to tvs was only 17%. The vast majority of artists ignored it on anything less than a giant circle. If it had been a larger stretch, they wouldn't have, and we would've had to choose between constant shape distortion or constant line distortion. As it is, our choice is much easier with rare shape distortion or constant line distortion.

**Comment by SourMesen** [comment]
Even with a database, I'd imagine a lot of this would come down to personal preference, too (someone might think game X looks better in 4:3 while someone else prefers it as 8:7).

For now, I'm not planning on implementing per-game settings (at least, not in the UI) - this typically makes the UI more complex and harder to use, and wouldn't have a whole lot of benefit in this case (not to mention the additional code complexity that comes with it.)

Something that could be done to make this easier might be to allow the user to select the aspect ratio from the options menu (rather than having to open up the video options), or maybe even customizable shortcuts to select aspect ratios - I'll add this to my list of potential improvements for the future.
