### ISSUE TITLE
Support Larger Cx4 ROMs (ROM Hacking)

### ISSUE THREAD

**Issue by Awakened0** [SourMesen/Mesen-S#75]
There's this rather nice Mega Man X3 hack called [Zero Project](https://www.romhacking.net/hacks/4086/). It works on SNES9x and the SD2SNES flashcart, but freezes on a black screen in Mesen-S and bsnes. Apparently it's because it uses a larger ROM than normal, according to [this post](https://www.romhacking.net/forum/index.php?topic=11130.msg382411#msg382411). I guess byuu never got around to adding support for it.

If implementing this is too messy/hacky/accuracy hurting I understand not bothering. Figured I'd at least bring it up since byuu was once open to it :)

**Comment by SourMesen** [comment]
Huh, looks like someone else brought this up before because I clearly remember taking a look at this already (but I can't find any trace of who it might have been.)

Fixing it is pretty trivial - haven't quite made up my mind yet, but I'm thinking of adding a general "Disable oversized ROM support (not recommended)" option for homebrew/romhacking purposes (and just always allow them for the libretro core)

**Comment by SourMesen** [comment]
Just added an option in emulation->advanced to turn on "strict" board mappings (not in the libretro core).  This romhack should be working properly by default now.

**Comment by Awakened0** [comment]
Awesome, thanks!
