### ISSUE TITLE
Full Throttle - All-American Racing (USA)

### ISSUE THREAD

**Issue by Max833** [SourMesen/Mesen-S#91]
Garbage on the last scanline. I can't see this on real hardware.
![image](https://user-images.githubusercontent.com/53529402/72550838-e285f800-3893-11ea-902d-92f508f7ec44.png)

**Comment by SourMesen** [comment]
Thanks for the report - this seems to be pretty similar to what the tests in #87 check.
There's a missing line below the buildings at the top, which also causes the extra line at the bottom.

The issue in Mesen-S' case is likely IRQ timing related, particularly after a WAI instruction.  I've managed to get the game fixed and the tests to look closer to what they should, but not quite there (and I'm not convinced the way I'm doing this is correct, either)

Really should just get a flash cart to run my own tests on.. (someday...)

**Comment by SourMesen** [comment]
This is fixed by 0ed96a04323db78b24ade1e11c3ab453b04ea4c7 (which also fixes A.S.P and makes the hdmaen_latch tests display something much closer to what's expected.

I'm unsure how valid/accurate the changes are, though (but I think they should at least be closer to what the timings are supposed to be, compared to before.) At the very least I haven't managed to find anything that was broken by the changes.  Will probably need to change this again later down the line.
