### ISSUE TITLE
Tengai Makyou Zero RTC

### ISSUE THREAD

**Issue by KZIII** [SourMesen/Mesen-S#98]
Thank you for supporting SPC7110.

About Tengai Makyou Zero RTC.
The day of the week is ahead one day.

may be

Rtc4513.cpp

_regs[12] = (newTm.tm_wday + 1) % 7;

>>>

_regs[12] = newTm.tm_wday % 7;

regards

**Comment by SourMesen** [comment]
Thanks for the report - this should be fixed by 26875e93ee000628ce72f8fdcf910f9cf0dee99f.

Just removing the +1 caused the RTC check on the first boot to fail, which was why I had put the +1 in the first place, but hadn't noticed the day of week was off by 1 in the game.  Hopefully should be working as expected for all dates now.
